CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE user_role AS ENUM ('student', 'teacher', 'admin');
CREATE TYPE course_member_role AS ENUM ('student', 'teacher');
CREATE TYPE submission_kind AS ENUM ('text', 'document', 'code', 'handwritten', 'mixed');
CREATE TYPE submission_status AS ENUM ('uploaded', 'processing', 'completed', 'failed');
CREATE TYPE plagiarism_verdict AS ENUM ('low_similarity', 'moderate_similarity', 'high_similarity', 'very_high_similarity');

CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name VARCHAR(150) NOT NULL, username CITEXT NOT NULL UNIQUE, email CITEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role user_role NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, email_verified BOOLEAN NOT NULL DEFAULT FALSE, last_login_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE courses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(200) NOT NULL, course_code VARCHAR(50), description TEXT, created_by UUID NOT NULL REFERENCES users(id), join_code VARCHAR(20) NOT NULL UNIQUE, is_archived BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE course_memberships (course_id UUID REFERENCES courses(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE CASCADE, member_role course_member_role NOT NULL, joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(course_id, user_id));
CREATE TABLE assignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE, created_by UUID NOT NULL REFERENCES users(id), title VARCHAR(250) NOT NULL, description TEXT, accepted_submission_type submission_kind NOT NULL DEFAULT 'document', due_at TIMESTAMPTZ, max_attempts INTEGER NOT NULL DEFAULT 1 CHECK(max_attempts > 0), is_published BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE submissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id UUID REFERENCES assignments(id) ON DELETE SET NULL, submitted_by UUID NOT NULL REFERENCES users(id), title VARCHAR(250), submission_type submission_kind NOT NULL, language VARCHAR(50), attempt_number INTEGER NOT NULL DEFAULT 1 CHECK(attempt_number > 0), status submission_status NOT NULL DEFAULT 'uploaded', pasted_content TEXT, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), processing_started_at TIMESTAMPTZ, processing_completed_at TIMESTAMPTZ, error_message TEXT, UNIQUE(assignment_id, submitted_by, attempt_number));
CREATE TABLE submission_files (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, original_filename VARCHAR(500) NOT NULL, stored_filename VARCHAR(500), mime_type VARCHAR(150), file_size_bytes BIGINT CHECK(file_size_bytes >= 0), storage_key TEXT, file_hash_sha256 CHAR(64), extracted_text TEXT, chroma_document_id VARCHAR(200), chroma_collection_name VARCHAR(200), uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE corpus_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL, course_id UUID REFERENCES courses(id) ON DELETE CASCADE, source_type VARCHAR(30) NOT NULL, title VARCHAR(500) NOT NULL, original_filename VARCHAR(500), source_url TEXT, storage_key TEXT, file_hash_sha256 CHAR(64), chroma_document_id VARCHAR(200) NOT NULL UNIQUE, chroma_collection_name VARCHAR(200) NOT NULL DEFAULT 'documents', chunk_count INTEGER NOT NULL DEFAULT 0 CHECK(chunk_count >= 0), is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE plagiarism_reports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, plagiarism_score NUMERIC(5,2) NOT NULL CHECK(plagiarism_score BETWEEN 0 AND 100), originality_score NUMERIC(5,2) NOT NULL CHECK(originality_score BETWEEN 0 AND 100), confidence_score NUMERIC(5,2) CHECK(confidence_score BETWEEN 0 AND 100), verdict plagiarism_verdict NOT NULL, summary TEXT, chunks_analysed INTEGER CHECK(chunks_analysed >= 0), citations JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE report_matches (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), report_id UUID NOT NULL REFERENCES plagiarism_reports(id) ON DELETE CASCADE, source_type VARCHAR(30) NOT NULL, matched_submission_id UUID REFERENCES submissions(id) ON DELETE SET NULL, corpus_document_id UUID REFERENCES corpus_documents(id) ON DELETE SET NULL, source_name VARCHAR(500) NOT NULL, source_url TEXT, similarity_score NUMERIC(5,2) NOT NULL CHECK(similarity_score BETWEEN 0 AND 100), matched_chunks INTEGER NOT NULL DEFAULT 0, sample_text TEXT, match_rank INTEGER, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE flagged_sections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), report_id UUID NOT NULL REFERENCES plagiarism_reports(id) ON DELETE CASCADE, report_match_id UUID REFERENCES report_matches(id) ON DELETE SET NULL, start_character INTEGER, end_character INTEGER, start_line INTEGER, end_line INTEGER, similarity_score NUMERIC(5,2) NOT NULL CHECK(similarity_score BETWEEN 0 AND 100), submitted_excerpt TEXT, matched_excerpt TEXT, reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_course_memberships_user ON course_memberships(user_id); CREATE INDEX idx_assignments_course ON assignments(course_id); CREATE INDEX idx_submissions_user ON submissions(submitted_by); CREATE INDEX idx_submission_files_submission ON submission_files(submission_id); CREATE INDEX idx_reports_submission ON plagiarism_reports(submission_id); CREATE INDEX idx_report_matches_report ON report_matches(report_id); CREATE INDEX idx_flagged_sections_report ON flagged_sections(report_id);
